version: "3.9"
services:
  backend:
    build: ./backend
    container_name: cricket-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: cricket-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4000"
